// Generated by CoffeeScript 1.9.3
(function() {
  this.Page = (function() {
    function Page(htmlElement, parentContext) {
      this.element = htmlElement;
      this.page = $(htmlElement);
      this._setPageSize();
      $(window).on('resize', this._setPageSize.bind(this));
    }

    Page.prototype._getWindowDimensions = function() {
      this.windowW = $(window).width();
      return this.windowH = $(window).height();
    };

    Page.prototype._setPageSize = function() {
      this._getWindowDimensions();
      this.page.height(this.windowH);
      return this.page.width(this.windowW);
    };

    Page.prototype.top = function() {
      return this.element.getBoundingClientRect().top;
    };

    Page.prototype.bottom = function() {
      return this.element.getBoundingClientRect().bottom;
    };

    Page.prototype.left = function() {
      return this.element.getBoundingClientRect().left;
    };

    Page.prototype.right = function() {
      return this.element.getBoundingClientRect().right;
    };

    Page.prototype.isActive = function() {
      if (this.top() === 0 && this.left() === 0) {
        return true;
      } else {
        return false;
      }
    };

    Page.prototype.getPageName = function() {
      var name;
      name = this.page.data('page-name');
      return String(name);
    };

    return Page;

  })();

}).call(this);
