// Generated by CoffeeScript 2.0.1
(function() {
  this.Page = class Page {
    constructor(htmlElement, hasAnimation) {
      this.mainContainer = $('.main--content--wrapper');
      this.element = htmlElement;
      this.page = $(htmlElement);
      this.hasAnimation = hasAnimation;
      this.pageAnimation = null;
      this._setPageSize();
      $(window).on('resize', this._setPageSize.bind(this));
    }

    _getWindowDimensions() {
      this.windowW = $(window).width();
      return this.windowH = $(window).height();
    }

    _setPageSize() {
      this._getWindowDimensions();
      this.page.height(this.windowH);
      return this.page.width(this.windowW);
    }

    top() {
      return this.element.getBoundingClientRect().top;
    }

    bottom() {
      return this.element.getBoundingClientRect().bottom;
    }

    left() {
      return this.element.getBoundingClientRect().left;
    }

    right() {
      return this.element.getBoundingClientRect().right;
    }

    isActive() {
      if (this.top() === 0 && this.left() === 0) {
        return true;
      } else {
        return false;
      }
    }

    getPageName() {
      var name;
      name = this.page.data('page-name');
      return String(name);
    }

    getWidth() {
      return this.page.width();
    }

    getHeight() {
      return this.page.height();
    }

    autoScrollToActivate() {
      var pageLeft, pageTop;
      pageTop = this.top();
      pageLeft = this.left();
      console.log("TOP ", pageTop);
      console.log("left", pageLeft);
      console.log("Main Container position ", this.mainContainer[0].getBoundingClientRect());
      this._destroyAnimation();
      if (pageTop > 0) {
        return TweenLite.to(this.mainContainer, 0.5, {
          top: -pageTop,
          ease: Power0.easeOut,
          onComplete: this._activateAnimation.bind(this)
        });
      } else if (pageTop < 0) {
        return TweenLite.to(this.mainContainer, 0.5, {
          top: 0,
          ease: Power0.easeOut,
          onComplete: this._activateAnimation.bind(this)
        });
      } else if (pageLeft > 0) {
        return TweenLite.to(this.mainContainer, 0.5, {
          left: -pageLeft,
          ease: Power0.easeOut,
          onComplete: this._activateAnimation.bind(this)
        });
      } else if (pageLeft < 0) {
        return TweenLite.to(this.mainContainer, 0.5, {
          left: 0,
          ease: Power0.easeOut,
          onComplete: this._activateAnimation.bind(this)
        });
      }
    }

    _activateAnimation() {
      var pa;
      if (this.hasAnimation) {
        this.pageAnimation = new PageAnimation();
        console.log(`PAGE animation is ${this.pageAnimation}`);
        pa = this.pageAnimation.lineAniamtion();
        return pa.play();
      }
    }

    _destroyAnimation() {
      if (this.pageAnimation) {
        return this.pageAnimation.destroyAnimation();
      }
    }

  };

}).call(this);
