// Generated by CoffeeScript 1.9.3
(function() {
  this.SilentParrot = (function() {
    function SilentParrot() {
      this.websiteWindow = $(window);
      this.mainWrapper = $('.universe--wrapper');
      this.pages = this.mainWrapper.find('.page');
      this.mainWrapperPosition = this._getWrapperSize();
      this.homePage = new Page(this.pages[0], this);
      this.aboutUsPage = new Page(this.pages[1], this);
      this.randomPage = new Page(this.pages[2], this);
      this.contactPage = new Page(this.pages[3], this);
      this.orderOfPages = [this.homePage, this.aboutUsPage, this.randomPage, this.contactPage];
      this.logo = this.mainWrapper.find('.logo--main');
      this.activePage = this.homePage;
      this.leftCounter = 0;
      this.topCounter = 0;
      this.mainWrapperTop = 0;
      this.windowW = 0;
      this.windowH = 0;
      this._onLoadHandler();
      $(window).on('hashchange', this._hashHandler.bind(this));
      this.websiteWindow.on('resize', this._resizeHandler.bind(this));
      $(window).on('mousewheel DOMMouseScroll', this._scrollHandler.bind(this));
      $(this.logo).on('mouseenter mouseleave', this._hoverHandler.bind(this));
    }

    SilentParrot.prototype._onLoadHandler = function() {
      this._getWindowDimensions();
      this._setWrapperSize();
      this._getActivePage();
      return this._getHash();
    };

    SilentParrot.prototype._hashHandler = function(e) {
      var newHash;
      newHash = window.location.hash;
      return newHash = newHash.replace(/#/g, '');
    };

    SilentParrot.prototype._resizeHandler = function() {
      this._getWindowDimensions();
      return this._setWrapperSize();
    };

    SilentParrot.prototype._scrollHandler = function(e) {
      if (e.originalEvent.wheelDelta > 0 || e.originalEvent.detail < 0) {
        console.log("Scrolled up");
        return this._scrollUp();
      } else {
        return this._scrollDown();
      }
    };

    SilentParrot.prototype._removeScrollHandler = function() {
      console.log("SCROLL handler removed ");
      return $(window).off('mousewheel DOMMouseScroll');
    };

    SilentParrot.prototype._addScrollHandler = function() {
      console.log("scroll handler added");
      return $(window).on('mousewheel DOMMouseScroll', this._scrollHandler.bind(this));
    };

    SilentParrot.prototype._hoverHandler = function() {
      var logoAnimation;
      logoAnimation = new LogoAnimation();
      return logoAnimation.mouseInAnimation();
    };

    SilentParrot.prototype._getWindowDimensions = function() {
      this.windowW = this.websiteWindow.width();
      return this.windowH = this.websiteWindow.height();
    };

    SilentParrot.prototype._setWrapperSize = function() {
      this.mainWrapper.css("width", this.windowW * 2);
      return this.mainWrapper.css("height", this.windowH * 2);
    };

    SilentParrot.prototype._getWrapperSize = function() {
      var wrapperSize;
      wrapperSize = this.mainWrapper[0].getBoundingClientRect();
      console.log("WRAPPER SIZE", wrapperSize);
      return wrapperSize;
    };

    SilentParrot.prototype._getActivePage = function() {
      var j, len, page, ref;
      ref = this.orderOfPages;
      for (j = 0, len = ref.length; j < len; j++) {
        page = ref[j];
        if (page.isActive()) {
          this._setHash(page);
          return page;
        }
      }
    };

    SilentParrot.prototype._getHash = function() {
      var hash;
      hash = window.location.hash;
      return this._setActivePage(hash);
    };

    SilentParrot.prototype._goToNextPageAutomatically = function(newActivePage) {
      var j, k, len, len1, oldActivePage, page, ref, ref1, results, results1;
      oldActivePage = this.activePage;
      if (newActivePage === "aboutUs") {
        ref = this.orderOfPages;
        results = [];
        for (j = 0, len = ref.length; j < len; j++) {
          page = ref[j];
          if (page.getPageName() === newActivePage) {
            this.activePage = page;
            results.push(this._scrollRight(oldActivePage, newActivePage));
          } else {
            results.push(void 0);
          }
        }
        return results;
      } else if (newActivePage === "contact") {
        ref1 = this.orderOfPages;
        results1 = [];
        for (k = 0, len1 = ref1.length; k < len1; k++) {
          page = ref1[k];
          if (page.getPageName() === newActivePage) {
            this.activePage = page;
            results1.push(this._scrollBottom(oldActivePage, newActivePage));
          } else {
            results1.push(void 0);
          }
        }
        return results1;
      }
    };

    SilentParrot.prototype._scrollRight = function(oldPage, newPage) {
      var scrollRight, scrollToNextPage;
      scrollRight = oldPage.getWidth();
      return scrollToNextPage = TweenLite.to(this.mainWrapper, 2.5, {
        x: -scrollRight,
        ease: Power1.easeOut
      });
    };

    SilentParrot.prototype._scrollBottom = function(oldPage, newPage) {
      var scrollBottom, scrollToNextPage;
      scrollBottom = oldPage.getHeight();
      return scrollToNextPage = TweenLite.to(this.mainWrapper, 2.5, {
        y: -scrollBottom,
        ease: Power1.easeOut
      });
    };

    SilentParrot.prototype._scrollDown = function() {
      var activePageName, mainWrapperPosition;
      activePageName = this.activePage.getPageName();
      console.log("active page is ", this.activePage);
      mainWrapperPosition = this.mainWrapper[0].getBoundingClientRect();
      if (activePageName === 'home') {
        this.leftCounter = this.leftCounter + 20;
        if (this.leftCounter <= 100) {
          TweenLite.to(this.mainWrapper, 0.4, {
            left: "-" + this.leftCounter + "%",
            ease: Power0.easeOut,
            onStart: this._removeScrollHandler.bind(this),
            onComplete: this._addScrollHandler.bind(this)
          });
        } else {
          console.log("Go to next page activated");
          this.leftCounter = 100;
          TweenLite.to(this.mainWrapper, 0.4, {
            left: "-" + this.leftCounter + "%",
            top: 0,
            ease: Power0.easeOut,
            onComplete: this._goToNextActivePage.bind(this)
          });
        }
      }
      if (activePageName === 'aboutUs') {
        this.topCounter = this.topCounter + 20;
        if (this.topCounter <= 100) {
          TweenLite.to(this.mainWrapper, 0.4, {
            top: "-" + this.topCounter + "%",
            ease: Power0.easeOut,
            onStart: this._removeScrollHandler.bind(this),
            onComplete: this._addScrollHandler.bind(this)
          });
        } else {
          this.topCounter = 100;
          TweenLite.to(this.mainWrapper, 0.4, {
            left: "-" + this.leftCounter + "%",
            top: "-" + this.topCounter + "%",
            ease: Power0.easeNone,
            onComplete: this._goToNextActivePage.bind(this)
          });
        }
      }
      if (activePageName === 'random') {
        this.leftCounter = this.leftCounter - 20;
        if (this.leftCounter >= 0) {
          TweenLite.to(this.mainWrapper, 0.4, {
            left: "-" + this.leftCounter + "%",
            ease: Power0.easeOut,
            onStart: this._removeScrollHandler.bind(this),
            onComplete: this._addScrollHandler.bind(this)
          });
        } else {
          this.leftCounter = 0;
          TweenLite.to(this.mainWrapper, 0.4, {
            left: this.leftCounter,
            top: "-" + this.topCounter + "%",
            ease: Power0.easeNone,
            onComplete: this._goToNextActivePage.bind(this)
          });
        }
      }
      if (activePageName === 'contact') {
        this.topCounter = this.topCounter - 20;
        if (this.topCounter >= 0) {
          return TweenLite.to(this.mainWrapper, 0.4, {
            top: "-" + this.topCounter + "%",
            ease: Power0.easeNone,
            onStart: this._removeScrollHandler.bind(this),
            onComplete: this._addScrollHandler.bind(this)
          });
        } else {
          this.topCounter = 0;
          return TweenLite.to(this.mainWrapper, 0.4, {
            left: 0,
            top: 0,
            ease: Power0.easeNone,
            onComplete: this._goToNextActivePage.bind(this)
          });
        }
      }
    };

    SilentParrot.prototype._scrollUp = function() {
      var activePageName, mainWrapperPosition;
      activePageName = this.activePage.getPageName();
      mainWrapperPosition = this.mainWrapper[0].getBoundingClientRect();
      if (activePageName === 'home') {
        this.leftCounter = this.leftCounter - 20;
        if (this.leftCounter > 0) {
          TweenLite.to(this.mainWrapper, 0.4, {
            left: "-" + this.leftCounter + "%",
            ease: Power0.easeOut,
            onStart: this._removeScrollHandler.bind(this),
            onComplete: this._addScrollHandler.bind(this)
          });
        } else {
          this.leftCounter = 0;
          TweenLite.to(this.mainWrapper, 0.4, {
            left: 0,
            top: 0,
            ease: Power0.easeNone,
            onComplete: this._goToPrevActivePage.bind(this)
          });
        }
      }
      if (activePageName === 'aboutUs') {
        this.topCounter = this.topCounter - 20;
        if (this.topCounter > 0) {
          TweenLite.to(this.mainWrapper, 0.4, {
            top: "-" + this.topCounter + "%",
            ease: Power0.easeNone,
            onStart: this._removeScrollHandler.bind(this),
            onComplete: this._addScrollHandler.bind(this)
          });
        } else {
          this.topCounter = 0;
          TweenLite.to(this.mainWrapper, 0.4, {
            left: "-" + this.leftCounter + "%",
            top: "-" + this.topCounter + "%",
            ease: Power0.easeNone,
            onComplete: this._goToPrevActivePage.bind(this)
          });
        }
      }
      if (activePageName === 'random') {
        this.leftCounter = this.leftCounter + 20;
        if (this.leftCounter < 100) {
          TweenLite.to(this.mainWrapper, 0.4, {
            left: "-" + this.leftCounter + "%",
            ease: Power0.easeNone,
            onStart: this._removeScrollHandler.bind(this),
            onComplete: this._addScrollHandler.bind(this)
          });
        } else {
          this.leftCounter = 100;
          TweenLite.to(this.mainWrapper, 0.4, {
            left: "-" + this.leftCounter + "%",
            top: "-" + this.topCounter + "%",
            ease: Power0.easeNone,
            onComplete: this._goToPrevActivePage.bind(this)
          });
        }
      }
      if (activePageName === 'contact') {
        this.topCounter = this.topCounter + 20;
        console.log("TOP COuNTER is ", this.topCounter);
        if (this.topCounter < 100) {
          return TweenLite.to(this.mainWrapper, 0.4, {
            top: "-" + this.topCounter + "%",
            ease: Power0.easeNone,
            onStart: this._removeScrollHandler.bind(this),
            onComplete: this._addScrollHandler.bind(this)
          });
        } else {
          this.topCounter = 100;
          return TweenLite.to(this.mainWrapper, 0.4, {
            left: 0,
            top: "-" + this.topCounter + "%",
            ease: Power0.easeNone,
            onComplete: this._goToPrevActivePage.bind(this)
          });
        }
      }
    };

    SilentParrot.prototype._goToNextActivePage = function() {
      var i, j, len, newActivePage, page, ref;
      newActivePage = null;
      ref = this.orderOfPages;
      for (i = j = 0, len = ref.length; j < len; i = ++j) {
        page = ref[i];
        if (page === this.activePage) {
          if (i + 1 < this.orderOfPages.length) {
            newActivePage = this.orderOfPages[i + 1];
          } else {
            newActivePage = this.orderOfPages[0];
          }
        }
      }
      if (newActivePage) {
        return this._setHash(newActivePage);
      }
    };

    SilentParrot.prototype._goToPrevActivePage = function() {
      var i, j, len, newActivePage, numOfPages, page, ref;
      newActivePage = null;
      ref = this.orderOfPages;
      for (i = j = 0, len = ref.length; j < len; i = ++j) {
        page = ref[i];
        if (page === this.activePage) {
          if (i >= 1) {
            newActivePage = this.orderOfPages[i - 1];
          } else {
            numOfPages = this.orderOfPages.length - 1;
            newActivePage = this.orderOfPages[numOfPages];
          }
        }
      }
      if (newActivePage) {
        return this._setHash(newActivePage);
      }
    };

    SilentParrot.prototype._setActivePage = function(hash) {
      return console.log("Set active page based on hash");
    };

    SilentParrot.prototype._setHash = function(newActivePage) {
      if (this.activePage !== newActivePage) {
        this.activePage = newActivePage;
        window.location.hash = this.activePage.getPageName();
      }
      return console.log("window location hash", window.location.hash);
    };

    return SilentParrot;

  })();

  $(function() {
    var silentParrot;
    return silentParrot = new SilentParrot();
  });

}).call(this);
